export const CREATE_NEW_BOARD = 'CREATE_NEW_BOARD';
export const CANCEL_NEW_BOARD = 'CANCEL_NEW_BOARD';
export const SUBMIT_NEW_BOARD = 'SUBMIT_NEW_BOARD';
export const RECEIVE_NEW_BOARD = 'RECEIVE_NEW_BOARD';
export const CLEAN_NEW_BOARD = 'CLEAN_NEW_BOARD';
